#!/bin/sh

# Enable syswatch
#----------------

logger -p local6.notice -t installer "app-network-core - enabling syswatch"
/sbin/chkconfig syswatch on >/dev/null 2>&1
/sbin/service syswatch start >/dev/null 2>&1

# Disable Avahi server
#---------------------

CHECK=`LANG=en_US /sbin/chkconfig --list avahi-daemon 2>&1 | /bin/grep 3:on`

if [ -x /usr/sbin/avahi-daemon ]; then
    logger -p local6.notice -t installer "app-network-core - disabling Avahi server"
    /sbin/chkconfig avahi-daemon off >/dev/null 2>&1
    /sbin/service avahi-daemon stop >/dev/null 2>&1
fi

# Disable PPPoE server
#---------------------

if [ -x /usr/sbin/pppoe-server ]; then
    logger -p local6.notice -t installer "app-network-core - disabling PPPoE server"
    /sbin/chkconfig pppoe-server off >/dev/null 2>&1
    /sbin/service pppoe-server stop >/dev/null 2>&1
fi

# Disable zeroconf
#-----------------

CHECK=`grep NOZEROCONF /etc/sysconfig/network 2>/dev/null`

if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-network-core - disabling zeroconf"
    echo "NOZEROCONF=\"yes\"" >> /etc/sysconfig/network
fi

# Set first NIC as external
#--------------------------

FIRST_NIC=`ip addr | grep ^2: | awk '{ print $2 }' | sed 's/://'`
if [ -n "$FIRST_NIC" ]; then
    logger -p local6.notice -t installer "app-network-core - setting external interface to $FIRST_NIC"
    sed -i -e "s/^EXTIF=.*/EXTIF=\"$FIRST_NIC\"/" /etc/clearos/network.conf

    # Make sure GATEWAYDEV is set
    #----------------------------

    CHECK=`grep "^GATEWAYDEV=" /etc/sysconfig/network 2>/dev/null`
    if [ -z $CHECK ]; then
        logger -p local6.notice -t installer "app-network-core - adding default gateway device"
        echo "GATEWAYDEV=\"$FIRST_NIC\"" >> /etc/sysconfig/network
    fi
fi

# Reload syswatch
#----------------

logger -p local6.notice -t installer "app-base-core - restarting syswatch"
service syswatch condrestart >/dev/null 2>&1
