#!/bin/sh

# Autofix the hostname
#---------------------

/usr/clearos/apps/network/deploy/autofix-hostname

# Dirty hack, sorry
#------------------

[ -x /usr/sbin/install-pro-extras ] && /usr/sbin/install-pro-extras

exit 0
